apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-svc-volume-claim
  labels:
    app: storage-svc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
