apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-svc
  template:
    metadata:
      labels:
        app: storage-svc
    spec:
      containers:
      - name: storage-svc
        image: ghcr.io/ua-tube/storage:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10000
        envFrom:
        - configMapRef:
            name: storage-svc-secret
        volumeMounts:
          - mountPath: /app/public
            name: storage-svcdata
      volumes:
        - name: storage-svcdata
          persistentVolumeClaim:
            claimName: storage-svc-volume-claim
