apiVersion: v1
kind: Service
metadata:
  name: storage-svc
  labels:
    app: storage-svc
spec:
  type: LoadBalancer
  ports:
  - port: 10000
    targetPort: 10000
    protocol: TCP
  selector:
    app: storage-svc
