apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-volume-claim
  labels:
    app: rabbitmq
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
