apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
  - name: http
    port: 15672
    protocol: TCP
  selector:
    app: rabbitmq
