apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-volume-claim
  labels:
    app: mongodb
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
