apiVersion: v1
kind: ConfigMap
metadata:
  name: search-svc-secret
  labels:
    app: search-svc
data:
  HTTP_HOST: '0.0.0.0'
  HTTP_PORT: '15700'
  RABBITMQ_URL: 'amqp://root:root@rabbitmq:5672'
  RABBITMQ_QUEUE: 'history'
  MEILISEARCH_URL: 'http://meilisearch:7700'
  MEILISEARCH_MASTERKEY: 'UaTubeMaster'
