apiVersion: v1
kind: Service
metadata:
  name: search-svc
  labels:
    app: search-svc
spec:
  type: ClusterIP
  ports:
  - port: 15700
    targetPort: 15700
    protocol: TCP
  selector:
    app: search-svc
