apiVersion: v1
kind: Service
metadata:
  name: community-svc
  labels:
    app: community-svc
spec:
  type: ClusterIP
  ports:
    - port: 15500
      targetPort: 15500
      protocol: TCP
  selector:
    app: community-svc
