apiVersion: v1
kind: Service
metadata:
  name: web-status
  labels:
    app: web-status
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 20000
      protocol: TCP
  selector:
    app: web-status
