version: '3.7'
services:
  postgres:
    restart: always
    volumes:
      - pg-data:/var/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATA: /var/data

  pgadmin:
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  rabbitmq:
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root

  mongo:
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'rs.initiate()']
      interval: 10s

  elasticsearch:
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx2g
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always

  logstash:
    restart: always
    environment:
      - ES_JAVA_OPTS=-Xmx1g
    volumes:
      - ./docker/logstash/pipeline:/usr/share/logstash/pipeline:ro,z
    depends_on:
      - elasticsearch
    ports:
      - 9600:9600
      - 9250:9250

  kibana:
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ES_JAVA_OPTS=-Xmx512m
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/usr/share/kibana/data

  redis:
    restart: always
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis-data:/data

  redis-commander:
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8083:8081
    depends_on:
      - redis
