apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-volume-claim
  labels:
    app: meilisearch
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
