apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
      - name: meilisearch
        image: getmeili/meilisearch:v1.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7700
        envFrom:
        - configMapRef:
            name: meilisearch-secret
        resources:
          requests:
            cpu: "500m"
            memory: "4Gi"
          limits:
            cpu: "2500m"
            memory: "20Gi"
        volumeMounts:
        - mountPath: /data.ms
          name: meilisearchdata
      volumes:
      - name: meilisearchdata
        persistentVolumeClaim:
          claimName: meilisearch-volume-claim
