apiVersion: v1
kind: PersistentVolume
metadata:
  name: meilisearch-volume
  labels:
    type: local
    app: meilisearch
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /data/meilisearch
