apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  labels:
    app: meilisearch
spec:
  type: ClusterIP
  ports:
  - port: 7700
    targetPort: 7700
    protocol: TCP
  selector:
    app: meilisearch
