apiVersion: v1
kind: Service
metadata:
  name: users-svc
  labels:
    app: users-svc
spec:
  type: ClusterIP
  ports:
  - port: 15400
    targetPort: 15400
    protocol: TCP
  selector:
    app: users-svc
