apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.13.0-management-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: amqp
          protocol: TCP
          containerPort: 5672
        - name: http
          protocol: TCP
          containerPort: 15672
        envFrom:
        - configMapRef:
            name: rabbitmq-secret
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2500m"
            memory: "5Gi"
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmqdata
      volumes:
      - name: rabbitmqdata
        persistentVolumeClaim:
          claimName: rabbitmq-volume-claim
