apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-processor-svc-volume-claim
  labels:
    app: video-processor-svc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
