apiVersion: v1
kind: PersistentVolume
metadata:
  name: video-processor-svc-volume
  labels:
    type: local
    app: video-processor-svc
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /data/video-processor-svc
