apiVersion: v1
kind: Service
metadata:
  name: video-processor-svc
  labels:
    app: video-processor-svc
spec:
  type: ClusterIP
  ports:
  - port: 11000
    targetPort: 11000
    protocol: TCP
  selector:
    app: video-processor-svc
