apiVersion: v1
kind: Service
metadata:
  name: library-svc
  labels:
    app: library-svc
spec:
  type: ClusterIP
  ports:
  - port: 15600
    targetPort: 15600
    protocol: TCP
  selector:
    app: library-svc
