apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        envFrom:
        - configMapRef:
            name: mongodb-secret
        volumeMounts:
        - mountPath: /data/db
          name: mongodbdata
      volumes:
      - name: mongodbdata
        persistentVolumeClaim:
          claimName: mongodb-volume-claim
