apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume-claim
  labels:
    app: redis
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
