apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
  labels:
    type: local
    app: redis
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /data/redis
