apiVersion: v1
kind: Service
metadata:
  name: video-manager-svc
  labels:
    app: video-manager-svc
spec:
  type: ClusterIP
  ports:
  - port: 15000
    targetPort: 15000
    protocol: TCP
  selector:
    app: video-manager-svc
