apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    app: auth-svc
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: auth-svc
