apiVersion: v1
kind: Service
metadata:
  name: history-svc
  labels:
    app: history-svc
spec:
  type: ClusterIP
  ports:
  - port: 15900
    targetPort: 15900
    protocol: TCP
  selector:
    app: history-svc
